Fix indenting

diff --git a/assets/aws-assume-role b/assets/aws-assume-role
--- a/assets/aws-assume-role
+++ b/assets/aws-assume-role
@@ -12,23 +12,22 @@ fi
 
 profile="${AWS_PROFILE:=default}"
 
-for var in "$@"
-do
+for var in "$@"; do
   case "$var" in
-    --profile)
-      profile="$2"
-      ;;
-    --account)
-      account="$2"
-      ;;
-    --role)
-      role="$2"
-      ;;
-    --duration)
-      duration="$2"
-      ;;
-    --help)
-      echo "Usage:
+  --profile)
+    profile="$2"
+    ;;
+  --account)
+    account="$2"
+    ;;
+  --role)
+    role="$2"
+    ;;
+  --duration)
+    duration="$2"
+    ;;
+  --help)
+    echo "Usage:
     --profile <string>   : Your AWS CLI profile, ie 'default'
     --account <string>   : The AWS Account where the role resides
     --role <string>      : The role to assume
@@ -38,8 +37,8 @@ Examples:
 aws-assume-role --account sandbox --role administrator --profile default --duration 600
 aws-assume-role < ~/account.json
       "
-      exit 0
-      ;;
+    exit 0
+    ;;
   esac
   shift
 done
@@ -48,53 +47,51 @@ done
 
 set_account() {
   # read accounts from json into a bash array
-  mapfile -t accounts < <(jq -r 'keys[]' <<< "$config")
+  mapfile -t accounts < <(jq -r 'keys[]' <<<"$config")
 
   if [[ ! -v account ]]; then
-      echo 'Which account are you accessing?'
-      select account in "${accounts[@]}"
-      do
-          break
-      done < /dev/tty # read from terminal (not /dev/stdin)
-      echo
-  fi
-  
-  if ! jq ."$account".id >/dev/null 2>&1 <<< "$config"; then
-      echo "Error - unknown account"
-      exit 1
+    echo 'Which account are you accessing?'
+    select account in "${accounts[@]}"; do
+      break
+    done </dev/tty # read from terminal (not /dev/stdin)
+    echo
   fi
 
-  account_id=$(jq -r ."$account".id  <<< "$config")
+  if ! jq ."$account".id >/dev/null 2>&1 <<<"$config"; then
+    echo "Error - unknown account"
+    exit 1
+  fi
+
+  account_id=$(jq -r ."$account".id <<<"$config")
 }
 
 set_role() {
   if [[ ! -v role ]]; then
-      # read accounts from json into a bash array
-      mapfile -t roles < <(jq -r ."$account".roles[]  <<< "$config")
+    # read accounts from json into a bash array
+    mapfile -t roles < <(jq -r ."$account".roles[] <<<"$config")
 
-      if [[ ${#roles[@]} == 1 ]]; then
-        echo "Only one role available...using role: ${roles[0]}"
-        role=${roles[0]}
-      else
-        echo "Which role do you want to assume?"
-        select role in "${roles[@]}"
-        do
-            break
-        done < /dev/tty # read from terminal (not /dev/stdin)
-      fi
-      echo
+    if [[ ${#roles[@]} == 1 ]]; then
+      echo "Only one role available...using role: ${roles[0]}"
+      role=${roles[0]}
+    else
+      echo "Which role do you want to assume?"
+      select role in "${roles[@]}"; do
+        break
+      done </dev/tty # read from terminal (not /dev/stdin)
+    fi
+    echo
   fi
 }
 
 set_duration() {
   if [[ ! -v duration ]]; then
-    minutes=$(jq -r ."$account".session_duration.minutes <<< "$config")
-    duration=$((minutes*60))
+    minutes=$(jq -r ."$account".session_duration.minutes <<<"$config")
+    duration=$((minutes * 60))
   fi
 }
 
 requires_mfa() {
-  jq ."$account".mfa <<< "$config"
+  jq ."$account".mfa <<<"$config"
 }
 
 get_session_token() {
@@ -114,14 +111,14 @@ fi
 
 echo "Assuming role..."
 response=$(aws sts assume-role \
-    --role-arn arn:aws:iam::"$account_id":role/"$role" \
-    --role-session-name "$account-session" \
-    --duration-seconds "$duration" \
-    --profile $profile)
+  --role-arn arn:aws:iam::"$account_id":role/"$role" \
+  --role-session-name "$account-session" \
+  --duration-seconds "$duration" \
+  --profile $profile)
 
-aws configure set profile."${account}".aws_access_key_id "$(jq -r .Credentials.AccessKeyId <<< "$response")"
-aws configure set profile."${account}".aws_secret_access_key "$(jq -r .Credentials.SecretAccessKey <<< "$response")"
-aws configure set profile."${account}".aws_session_token "$(jq -r .Credentials.SessionToken <<< "$response")"
+aws configure set profile."${account}".aws_access_key_id "$(jq -r .Credentials.AccessKeyId <<<"$response")"
+aws configure set profile."${account}".aws_secret_access_key "$(jq -r .Credentials.SecretAccessKey <<<"$response")"
+aws configure set profile."${account}".aws_session_token "$(jq -r .Credentials.SessionToken <<<"$response")"
 
 echo "Profile: ${account}"
-jq . <<< "$response"
+jq . <<<"$response"
